---
# X-COM UFO Desense role task
# This collection of tasks will install and configure X-COM UFO 
# Defense to run with the open-source project openxcom


- name: Installing...
  ansible.builtin.include_role:
      name: install


- name: Configure shortcuts to launch game from ChromeOS app menu
  block:


      - name: Download Icon assets from smoke-resources repository
        ansible.builtin.get_url:
            url: "{{ icon_url }}/{{ item }}"
            dest: "{{ icon_dir }}/{{ item }}"
            force: no
        loop: "{{ icons }}"

      - name: Create Desktop entry
        ansible.builtin.template:
            src: xcom_ufo_defense.desktop.j2
            dest: "{{ app_dir }}/xcom-ufo-defense.desktop"
