---
# X-COM UFO Desense role task
# This collection of tasks will install and configure X-COM UFO 
# Defense to run with the open-source project openxcom


- name: Installing...
  ansible.builtin.include_role:
      name: install