# Variables for the X-COM UFO Defense installer

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: { 
    path: "{{ home }}/setup_freespace_2_1.20_v2_(33372).exe",
    convert_filename_lowercase: False,
    type: innosetup
    }

# Game base directory
# format:
# #   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.freespace2"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}/FS2/data/movies"
    - "{{ base_dir }}/FS2/data/players"

# Install record
# If this file exists, the installer will skip extracting the game content
install_record: "{{ smoke_config_dir }}/freespace2"

# Game files list with source and destination
# Note {{ tmp_dir.path }} must be prefixed to the src location
game_files:
  - { src: "Root_fs2.vp", dest: "{{ base_dir }}/FS2/Root_fs2.vp" }
  - { src: "smarty_fs2.vp", dest: "{{ base_dir }}/FS2/smarty_fs2.vp" }
  - { src: "sparky_fs2.vp", dest: "{{ base_dir }}/FS2/sparky_fs2.vp" }
  - { src: "sparky_hi_fs2.vp", dest: "{{ base_dir }}/FS2/sparky_hi_fs2.vp" }
  - { src: "stu_fs2.vp", dest: "{{ base_dir }}/FS2/stu_fs2.vp" }
  - { src: "tango1_fs2.vp", dest: "{{ base_dir }}/FS2/tango1_fs2.vp" }
  - { src: "tango2_fs2.vp", dest: "{{ base_dir }}/FS2/tango2_fs2.vp" }
  - { src: "tango3_fs2.vp", dest: "{{ base_dir }}/FS2/tango3_fs2.vp" }
  - { src: "warble_fs2.vp", dest: "{{ base_dir }}/FS2/warble_fs2.vp" }