---
# Variables for the openxcom appimage installer

# OpenXcom base directories
base_dir: "{{ home }}/.freespace2"

# Directories needed for openxcom games
directories:
    - "{{ home }}/.local/share/appimagekit"
    - "{{ base_dir }}/bin"
    - "{{ icon_dir }}"
    - "{{ app_dir }}"

freespace_open_url: https://github.com/scp-fs2open/fs2open.github.com/releases/download/release_22_2_0/fs2_open_22_2_0-builds-Linux.tar.gz
freespace_open_appImage: fs2_open_22_2_0_x64.AppImage
 
