---
# Sam & Max: Hit the Road role task
# This collection of tasks will install and configure Sam & Max:
# Hit the Road to run with the open-source
# game engine ScummVM.


- name: Install ScummVM
  ansible.builtin.import_role:
      name: scummvm

- name: Installing...
  ansible.builtin.include_role:
      name: install

- name: Insert Sam and Max hit the road game to scummvm
  ansible.builtin.blockinfile:
      path: "{{ home }}/.config/scummvm/scummvm.ini"
      block: |
          [samnmax]
          gameid=samnmax
          description=Sam & Max Hit the Road (CD/English)
          language=en
          extra=CD
          path={{ base_dir }}
          enable_enhancements=true
          engineid=scumm
          guioptions=gameOption2 lang_English
      state: present
      marker: "# {mark} SAMNMAX BLOCK INSERTED BY SMOKE"

- name: Create Desktop Entry
  ansible.builtin.template:
      src: samnmax.desktop.j2
      dest: "{{ app_dir }}/samnmax.desktop"
