---
# Contrib role
# This role will add the contrib debian repo to your system.
#
# Games requiring packages from this repo should import this role into their
# main playbook.
#
#   - name: Import debian contrib repo
#     ansible.builtin.include_role:
#         name: contib

- name: Add contrib repo to apt
  become: yes
  ansible.builtin.apt_repository:
      repo: "{{ item }}"
      state: present
  loop:
      - "deb https://deb.debian.org/debian bullseye contrib"
      - "deb https://deb.debian.org/debian bullseye-updates contrib"
      - "deb https://deb.debian.org/debian-security/ bullseye-security contib"

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
      update_cache: yes
    
