---
# Descent 2 role tasks
# This collection of tasks will install and configure Descent 2
# to run with the open-source engine d2x-rebirth.
#
# Known bug:
# Certain Descent movies are not playing. This is related to a problem
# introduced with PhysFS 3 - details are listed in the link below.
# https://github.com/dxx-rebirth/dxx-rebirth/issues/379
#
# Note: debian bullseye install PhysFS 3.0.2-5
# https://packages.debian.org/bullseye/libphysfs
#
# debian bullseye installs d2x-rebirth 0.58.1-1.3
# https://packages.debian.org/bullseye/d2x-rebirth1

- name: Add non-free repository for d2x-rebirth
  ansible.builtin.import_role:
      name: non_free

- name: Installing...
  ansible.builtin.include_role:
      name: install

- name: Create descent.cfg file
  ansible.builtin.template:
      src: descent.cfg.j2
      dest: "{{ base_dir }}/descent.cfg"
