---
# Collects information about your system to help configure

# Screen width variable "{{ screen_width.stdout }}"
- name: Screen width
  ansible.builtin.shell: xrandr|grep '*'|head -n 1|awk '{print $1}'|cut -d\x -f1
  register: screen_width

# Screen height variable "{{ screen_height.stdout }}"
- name: Screen height
  ansible.builtin.shell: xrandr|grep '*'|head -n 1|awk '{print $1}'|cut -d\x -f2
  register: screen_height
