---
# Collect information about your system to help configure installation
#
# There are no pre-requisites to including this task list.
#
# Once complete, you will be able to access the following information
#
# {{ screen_width.stdout }} = screen resolution width in pixels
# {{ screen_height.stdout }} = screen resolution height in pixels
#
# Use the following format to include this task list:
#
#   - name: Collect system information
#     ansible.builtin.include_tasks: common/tasks/collect_system_info.yml


- name: Screen width
  ansible.builtin.shell: xrandr|grep '*'|head -n 1|awk '{print $1}'|cut -d\x -f1
  register: screen_width
  changed_when: false

- name: Screen height
  ansible.builtin.shell: xrandr|grep '*'|head -n 1|awk '{print $1}'|cut -d\x -f2
  register: screen_height
  changed_when: false
