---
# Standard extracting command for mojosetup files
#
# {{ tmp_dir.path }} must be registered before including this task list.
#
# {{ installer }} must be registered befor including this task list.
#   installer: {
#       path: "/full/path/to/installer.sh"
#       sha1sum: hash of the file goes here
#   }
#
#   The system must have unzip installed to support this
#
#   Use the following format to include this task list:
#
#     - name: Extract game files with unzip
#       ansible.bultin.include_tasks: common/tasks/extract_mojosetup.yml

- name: Extract game installer into working directory
  ansible.builtin.command:
      argv:
          - unzip
          - -d
          - "{{ tmp_dir.path |quote }}"
          - "{{ installer.path }}"
  register: result
  failed_when: result.rc > 1
