---
# This tast list will extract music tracks from a cd image and convert
# it to a ogg format.

- name: Extract music tracks from CD images
  ansible.builtin.command:
      argv:
          - bchunk
          - -w
          - "{{ tmp_dir.path }}/{{ item.bin }}"
          - "{{ tmp_dir.path }}/{{ item.cue }}"
          - "{{ item.dest }}/track"


- name: Delete the first track from the CD image
  block:

    - name: Find data tracks
      ansible.builtin.find:
          paths: "{{ item.dest }}"
          patterns: "track01.iso"
      register: files_to_delete

    - name: Remove data tracks
      ansible.builtin.file:
          path: "{{ file_item.path }}"
          state: absent
      loop: "{{ files_to_delete.files }}"
      loop_control:
          loop_var: file_item 
          label: "{{ file_item.path }}"


- name: Convert WAV files to OGG
  block:

    - name: Find WAV files
      ansible.builtin.find:
          paths: "{{ item.dest }}"
          patterns: "*.wav"
      register: wave_files

    - name: Convert WAV files to OGG
      ansible.builtin.command:
          argv:
            - oggenc
            - -Q
            - -q
            - 8
            - "{{ file_item.path }}"
      loop: "{{ wave_files.files }}"
      loop_control:
          loop_var: file_item
          label: "{{ file_item.path }}"

    - name: Delete WAV files
      ansible.builtin.file:
          path: "{{ file_item.path }}"
          state: absent
      loop: "{{ wave_files.files }}"
      loop_control:
          loop_var: file_item
          label: "{{ file_item.path }}"
