---
# These tasks should be included in the role's main task listing before installing.

- name: Locate install file in home directory
  ansible.builtin.stat:
    path: "{{ home }}/{{ installer }}"
  register: install_file

- name: Abort install if install file not found
  ansible.builtin.fail:
    msg: "Install file {{ home }}/{{ installer }} not found.  Please download installer and try again."
  when: not install_file.stat.exists

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    state: present

- name: Create directory tree for game files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ directories }}"
