---
# Perform rudimentary checks on the system before attempting to install
#
# {{ installer }} must be registered before including this task list.
#   installer: {
#     path: "/full/path/to/setup.exe"
#     sha1sum: hash of the file goes here
#   }
#
# {{ dependencies }} must be registered before including this task list.
#   dependencies:
#     - package-name1
#     - package-name2
#
# {{ directories }} must be registered before including this task list.
#   directories:
#     - /full/path/to/game_files
#     - /full/path/to/game_configs
#
# Use the following format to include this task list:
#
#   - name: System pre-install checks
#     ansible.builtin.include_tasks: common/tasks/pre_install.yml


- name: Locate install file in home directory
  ansible.builtin.stat:
    path: "{{ installer.path }}"
  register: install_file

- name: Abort install if install file not found
  ansible.builtin.fail:
    msg: "Install file {{ installer.path }} not found.  Please download installer and try again."
  when: not install_file.stat.exists

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    state: present

- name: Create directory tree for game files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ directories }}"
