---
# OpenXcom role task
# This collection of tasks will install and configure OpenXcom AppImage
# from github.  It does not contain any game configurations for UFO Defense
# or Terror from the Deep, but it is required before these games can be
# installed.
#
# Import this role in the main tasks of your games that run on this engine.
#
#   - name: Install OpenXcom
#     ansible.builtin.import_role:
#         name: openxcom
#


# Collect screen resolution for deployment of options.cfg
# Re-use the create_directories tasks from install
# Re-use the download_icons to download the OpenXcom icon from smoke-resources
- name: Include tasks from install role for deployment
  ansible.builtin.include_role: 
      name: install
      tasks_from: "{{ item }}"
  loop:
      - collect_system_info
      - create_directories
      - download_icons

- name: Check system for OpenXcom AppImage file
  ansible.builtin.stat:
      path: "{{ base_dir }}/{{ openxcom_file }}"
  register: is_openxcom_installed

- name: Only download and install the OpenXcom AppImage if it is not present on the system
  block:

      - name: Download OpenXcom AppImage
        ansible.builtin.get_url:
            url: "{{ openxcom_url }}/{{ openxcom_file }}"
            dest: "{{ base_dir }}/{{ openxcom_file }}"
            mode: "0755"
            force: no

  when: not is_openxcom_installed.stat.exists


- name: Disable prompt to integrate AppImage with the system menu
  ansible.builtin.file:
      path: "{{ home }}/.local/share/appimagekit/OpenXcom_no_desktopintegration"
      state: touch
      mode: "0644"
      modification_time: preserve
      access_time: preserve

- name: Deploy option.cfg template to openxcom folder
  ansible.builtin.template:
      src: options.cfg.j2
      dest: "{{ config_dir }}/options.cfg"

- name: Create Desktop Entry
  ansible.builtin.template:
      src: openxcom.desktop.j2
      dest: "{{ app_dir }}/openxcom.desktop"
