---
# Theme Hospital role tasks
# This collection of tasks will install and configure Theme Hospital
# to run with the open-source engine corsix-th


- name: Initial system checks before installation
  block:

      - name: Collect screen resolution to use in config.txt
        ansible.builtin.include_tasks: common/tasks/collect_system_info.yml

      - name: Add contrib repository
        ansible.builtin.include_tasks: common/tasks/add_repo.yml

      - name: Pre-Install check list
        ansible.builtin.include_tasks: common/tasks/pre_install.yml

      - name: Skip extracting installer if game file found on system
        ansible.builtin.stat:
            path: "{{ base_dir }}/somefile"
        register: is_game_installed


- name: Extract and configure game files from the installer
  block:

      - name: Create temporary working directory for installation files
        ansible.builtin.tempfile:
            state: directory
        register: tmp_dir

      # Corsix is case sensitive, the default extractor task sets all files to
      # lowercase
      - name: Use innoextract to extract game files
        ansible.builtin.command:
            argv:
                - innoextract
                - -s
                - -m
                - -d
                - "{{ tmp_dir.path }}"
                - "{{ installer.path }}"

      - name: Copy game files from the temporary directory
        ansible.builtin.include_tasks: common/tasks/copy_files.yml
        loop: "{{ game_files }}"
        loop_control:
            label: "{{ item.dest }}"


  when: not is_game_installed.stat.exists
  always:

      - name: Delete the temporary working directory
        ansible.builtin.file:
            path: "{{ tmp_dir.path }}"
            state: absent
        when: tmp_dir.path is defined

- name: Configure shortcuts to launch the game from ChromeOS app menu
  block:

      - name: Deploy config.txt file
        ansible.builtin.template:
            src: config.txt.j2
            dest: "{{ base_dir }}/config.txt"
