---
# Theme Hospital role tasks
# This collection of tasks will install and configure Theme Hospital
# to run with the open-source engine corsix-th


- name: Add contrib debian repo for CorsixTH
  ansible.builtin.import_role: 
      name: contrib

- name: Installing...
  ansible.builtin.include_role:
      name: install

- name: Configure shortcuts to launch the game from ChromeOS app menu
  block:

      - name: Deploy config.txt file
        ansible.builtin.template:
            src: config.txt.j2
            dest: "{{ base_dir }}/config.txt"
