# Variables for the Arcane Dimensions installer

# Mod file
mod_url: https://www.quaddicted.com/filebase/ad_v1_80p1final.zip

# Game base directory
# format:
# #   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.quake"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}/ad"
