---
# Quake role task
# This collection of tasks will install and configure Quake: The Offering
# and the expansion packs, Scourge of Armagon and Dissolution of Eternity,
# to run with the open-source engine Quakespasm-Spiked.


- name: Install QuakeSpasm-Spiked engine
  ansible.builtin.import_role:
      name: quakespasm_spiked

- name: Installing...
  ansible.builtin.include_role:
      name: install

- name: Configure shortcuts to launch game from ChromeOS app menu
  block:

    - name: Create Desktop entries
      ansible.builtin.template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
      loop:
          - { src: quake.desktop.j2, dest: "{{ app_dir }}/quake.desktop" }
          - { src: quake-soa.desktop.j2, dest: "{{ app_dir }}/quake-soa.desktop" }
          - { src: quake-doe.desktop.j2, dest: "{{ app_dir }}/quake-doe.desktop" }
      loop_control:
          label: "{{ item.dest }}"

    - name: Deploy config.cfg files
      ansible.builtin.template:
          src: config.cfg.j2
          dest: "{{ item }}"
      with_items:
          - "{{ base_dir }}/id1/config.cfg"
          - "{{ base_dir }}/hipnotic/config.cfg"
          - "{{ base_dir }}/rogue/config.cfg"
