# Variables for the indiana jones and the fate of atlantis installer

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: { 
    path: "{{ home }}/sam_and_max_hit_the_road_en_gog_2_20100.sh",
    sha1sum: 8055a8586b88d6d5f38f32ac4b0c6d1f8646426f,
    convert_filename_lowercase: False,
    type: mojosetup
    }

# Game base directory
# format:
# #   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.scummvm/samnmax"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}"

# Install record
# If this file exists, the installer will skip extracting the game content
install_record: "{{ smoke_config_dir }}/samnmax"

# Game files list with source and destination
# Note {{ tmp_dir.path }} must be prefixed to the src location
game_files:
  - { src: "data/noarch/data/monster.sou", dest: "{{ base_dir }}/monster.sou" }
  - { src: "data/noarch/data/samnmax.001", dest: "{{ base_dir }}/samnmax.001" }
  - { src: "data/noarch/data/samnmax.000", dest: "{{ base_dir }}/samnmax.000" }
  - { src: "data/noarch/support/icon.png", dest: "{{ icon_dir }}/samnmax.png" }
