# Variables for the X-COM UFO Defense installer

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: { 
    path: "{{ home }}/setup_x-com_ufo_defense_1.2_(28046).exe",
    sha1sum: 49bf8cbed3d662b6e5e16b87245d69599d4c22c1,
    convert_filename_lowercase: True,
    type: innosetup
    }

# Game base directory
# format:
# #   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.local/share/openxcom/UFO"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}/geodata"
    - "{{ base_dir }}/geograph"
    - "{{ base_dir }}/maps"
    - "{{ base_dir }}/routes"
    - "{{ base_dir }}/sound"
    - "{{ base_dir }}/terrain"
    - "{{ base_dir }}/ufograph"
    - "{{ base_dir }}/ufointro"
    - "{{ base_dir }}/units"

# Install record
# If this file exists, the installer will skip extracting the game content
install_record: "{{ smoke_config_dir }}/ufo_defense"

# Game files list with source and destination
# Note {{ tmp_dir.path }} must be prefixed to the src location
game_files:
  - { src: "geodata/", dest: "{{ base_dir }}/geodata/" }
  - { src: "geograph/", dest: "{{ base_dir }}/geograph/" }
  - { src: "maps/", dest: "{{ base_dir }}/maps/" }
  - { src: "routes/", dest: "{{ base_dir }}/routes/" }
  - { src: "sound/", dest: "{{ base_dir }}/sound/" }
  - { src: "terrain/", dest: "{{ base_dir }}/terrain/" }
  - { src: "ufograph/", dest: "{{ base_dir }}/ufograph/" }
  - { src: "ufointro/", dest: "{{ base_dir }}/ufointro/" }
  - { src: "units/", dest: "{{ base_dir }}/units/" }
