# Variables for the X-COM UFO Defense installer

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: { 
    path: "{{ home }}/setup_x-com_ufo_defense_1.2_(28046).exe",
    sha1sum: 49bf8cbed3d662b6e5e16b87245d69599d4c22c1,
    convert_filename_lowercase: True,
    type: innosetup
    }

# Dependencies
dependencies:
    - innoextract

# Quake base directory
base_dir: "{{ home }}/.local/share/openxcom/UFO"

# Directory trees to be created on the system
directories:
    - "{{ base_dir }}/geodata"
    - "{{ base_dir }}/geograph"
    - "{{ base_dir }}/maps"
    - "{{ base_dir }}/routes"
    - "{{ base_dir }}/sound"
    - "{{ base_dir }}/terrain"
    - "{{ base_dir }}/ufograph"
    - "{{ base_dir }}/ufointro"
    - "{{ base_dir }}/units"

# Sanity file
sanity_file: "{{ base_dir }}/geodata/world.dat"

# Game files list with source and destination
# Note {{ tmp_dir.path }} must be prefixed to the src location
game_files:
  - { src: "geodata/", dest: "{{ base_dir }}/geodata/" }
  - { src: "geograph/", dest: "{{ base_dir }}/geograph/" }
  - { src: "maps/", dest: "{{ base_dir }}/maps/" }
  - { src: "routes/", dest: "{{ base_dir }}/routes/" }
  - { src: "sound/", dest: "{{ base_dir }}/sound/" }
  - { src: "terrain/", dest: "{{ base_dir }}/terrain/" }
  - { src: "ufograph/", dest: "{{ base_dir }}/ufograph/" }
  - { src: "ufointro/", dest: "{{ base_dir }}/ufointro/" }
  - { src: "units/", dest: "{{ base_dir }}/units/" }
