# Variables for the Quake 2 installer

# Install file from gog
installer: {
    path: "{{ home }}/setup_quake2_quad_damage_2.0.0.3.exe",
    sha1sum: 95692ee89f3a4376ca447266044e114ed0c5339,
    convert_filename_lowercase: False
    }
    
# Dependencies
dependencies:
    - yamagi-quake2
    - mesa-utils
    - innoextract

# Quake 2 base directory
base_dir: "{{ home }}/.yq2"

# Directories to be created on the system
directories:
    - "{{ base_dir }}/baseq2/video"
    - "{{ base_dir }}/xatrix/video"
    - "{{ base_dir }}/rogue/video"
    - "{{ base_dir }}/music"
    - "{{ base_dir }}/ctf"
    - "{{ icon_dir }}"
    - "{{ app_dir }}"

# Sanity File
sanity_file: "{{ base_dir }}/baseq2/pak0.pak"

# Game files list with source and destination
# Note: {{ tmp_dir.path }} must be prefixed ot the src location.
game_files:
  # Pak files
  - { src: "app/baseq2/pak0.pak", dest: "{{ base_dir }}/baseq2/pak0.pak" }
  - { src: "app/baseq2/pak1.pak", dest: "{{ base_dir }}/baseq2/pak1.pak" }
  - { src: "app/baseq2/pak2.pak", dest: "{{ base_dir }}/baseq2/pak2.pak" }
  - { src: "app/rogue/pak0.pak", dest: "{{ base_dir }}/rogue/pak0.pak" }
  - { src: "app/xatrix/pak0.pak", dest: "{{ base_dir }}/xatrix/pak0.pak" }
  - { src: "app/ctf/pak0.pak", dest: "{{ base_dir }}/ctf/pak0.pak" }
  # Video files
  - { src: "app/baseq2/video/", dest: "{{ base_dir }}/baseq2/video/" }
  - { src: "app/rogue/video/", dest: "{{ base_dir }}/rogue/video/" }
  - { src: "app/xatrix/video/", dest: "{{ base_dir }}/xatrix/video/" }
  # Music files
  - { src: "app/music/", dest: "{{ base_dir }}/music/" }

# Additional resources
smoke_resources: https://raw.githubusercontent.com/gooseberry/smoke-resources/main/quake2

icons:
    - quake2.png
    - quake2-the-reckoning.png
    - quake2-ground-zero.png
