# Variables for the Quake 2 installer

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: {
    path: "{{ home }}/setup_quake2_quad_damage_2.0.0.3.exe",
    sha1sum: 95692ee89f3a4376ca447266044e114ed0c5339,
    convert_filename_lowercase: False,
    type: innosetup
    }
    
# List of dependencies needed to run the game.
# format:
#   - package1
#   - package2
dependencies:
    - yamagi-quake2
    - mesa-utils

# Game base directory
# format:
# #   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.yq2"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}/baseq2/video"
    - "{{ base_dir }}/xatrix/video"
    - "{{ base_dir }}/rogue/video"
    - "{{ base_dir }}/music"
    - "{{ base_dir }}/ctf"

# Install record
# If this file exists, the installer will skip extracting the game content
install_record: "{{ smoke_config_dir }}/quake2"

# Game files list with source and destination
# Note: {{ tmp_dir.path }} must be prefixed ot the src location.
game_files:
  # Pak files
  - { src: "app/baseq2/pak0.pak", dest: "{{ base_dir }}/baseq2/pak0.pak" }
  - { src: "app/baseq2/pak1.pak", dest: "{{ base_dir }}/baseq2/pak1.pak" }
  - { src: "app/baseq2/pak2.pak", dest: "{{ base_dir }}/baseq2/pak2.pak" }
  - { src: "app/rogue/pak0.pak", dest: "{{ base_dir }}/rogue/pak0.pak" }
  - { src: "app/xatrix/pak0.pak", dest: "{{ base_dir }}/xatrix/pak0.pak" }
  - { src: "app/ctf/pak0.pak", dest: "{{ base_dir }}/ctf/pak0.pak" }
  # Video files
  - { src: "app/baseq2/video/", dest: "{{ base_dir }}/baseq2/video/" }
  - { src: "app/rogue/video/", dest: "{{ base_dir }}/rogue/video/" }
  - { src: "app/xatrix/video/", dest: "{{ base_dir }}/xatrix/video/" }
  # Music files
  - { src: "app/music/", dest: "{{ base_dir }}/music/" }

# Icon filenames stored on the smoke-repository git that should be downloaded to the
# {{ icon_dir }} to create desktop icons.
icons:
    - quake2.png
    - quake2-the-reckoning.png
    - quake2-ground-zero.png
