---
# Terminal Velocity role task
# This collection of tasks will install and configure
# Terminal Velocity to run with the open-source
# game engine DosBox.


- name: Install DosBox
  ansible.builtin.import_role:
      name: dosbox

- name: Installing...
  ansible.builtin.include_role:
      name: install

- name: Create Custom DosBox Configuration
  ansible.builtin.template:
      src: terminal_velocity.conf.j2
      dest: "{{ base_dir }}/config/terminal_velocity.conf"

- name: Create Desktop Entry
  ansible.builtin.template:
      src: terminal_velocity.desktop.j2
      dest: "{{ app_dir }}/terminal_velocity.desktop"
