---
# OpenXcom role task
# This collection of tasks will install and configure OpenXcom AppImage
# from github.  It does not contain any game configurations for UFO Defense
# or Terror from the Deep, but it is required before these games can be
# installed.
#
# Import this role in the main tasks of your games that run on this engine.
#
#   - name: Install OpenXcom
#     ansible.builtin.import_role:
#         name: openxcom
#


# Collect screen resolution for deployment of options.cfg
# Re-use the create_directories tasks from install
# Re-use the download_icons to download the OpenXcom icon from smoke-resources
- name: Include tasks from install role for deployment
  ansible.builtin.include_role: 
      name: install
      tasks_from: "{{ tasks }}"
  loop:
      - create_directories
  loop_control:
      loop_var: tasks

- name: Only download and install the FreeSpaceOpen AppImage if it is not present on the system
  block:

      - name: Download FreeSpaceOpen AppImage
        ansible.builtin.unarchive:
            src: "{{ freespace_open_url }}"
            dest: "{{ base_dir }}/bin"
            mode: "0755"
            remote_src: yes
            creates: "{{ base_dir}}/bin/{{ freespace_open_appImage }}"


