---
# Quake 2 role task
# This collection of tasks will install and configure Quake 2
# and the expansion packs, The Reckoning, and Ground Zero to 
# run with the open source engine Yamagi.


- name: Add contrib repository
  ansible.builtin.import_role:
      name: contrib

- name: Installing...
  ansible.builtin.include_role:
    name: install

- name: Configure shortcuts to launch game from ChromeOS app meny
  block:

      - name: Download Icon assets from smoke-resource repository
        ansible.builtin.get_url:
            url: "{{ icon_url }}/{{ item }}"
            dest: "{{ icon_dir }}/{{ item }}"
            force: no
        loop: "{{ icons }}"

      - name: Create Desktop entries
        ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
        loop:
            - { src: quake2.desktop.j2, dest: "{{ app_dir }}/quake2.desktop" }
            - { src: quake2-the-reckoning.desktop.j2, dest: "{{ app_dir }}/quake2-the-reckoning.desktop" }
            - { src: quake2-ground-zero.desktop.j2, dest: "{{ app_dir }}/quake2-ground-zero.desktop" }

      - name: Deploy config.cfg files
        ansible.builtin.template:
            src: config.cfg.j2
            dest: "{{ item }}"
        loop:
            - "{{ base_dir }}/baseq2/config.cfg"
            - "{{ base_dir }}/xatrix/config.cfg"
            - "{{ base_dir }}/rogue/config.cfg"
