---
# Descent 2 specific variables

# installer
# parameters:
#   - path:         Required    full path to the install file.
#   - sha1sum:      Optional    not used. planned to check file integrity in future
#   - convert_filename_lowercase: Required  set to true if filenames need to be
#                                           converted to lowercase.
#   - type:         Required    acceptable values: mojosetup, innosetup
installer: {
    path: "{{ home }}/setup_descent_2_1.1_(16596).exe",
    sha1sum: 362773ad0094cb5134e10bf7f401bb1344daeea9,
    convert_filename_lowercase: True,
    type: innosetup
    }

# List of dependencies needed to run the game.
# format:
#   - package1
#   - package2
dependencies:
    - d2x-rebirth
    - mesa-utils
      
# Game base directory
# format:
#   base_dir: /full/path/to/where/game/files/should/be/installed
base_dir: "{{ home }}/.d2x-rebirth"

# List of directories that need to be created on the system.
# The builtin.copy module will not create directories.  You must list
# all destination directories here.
# format:
#   directories:
#       - /first/path
#       - /second/path
directories:
    - "{{ base_dir }}/music"

# Install record
# If this file exists, the installer will skip extracting the game content
install_record: "{{ smoke_config_dir }}/descent2"
  
# Game files lists with source and destination
# Note {{ tmp_dir.path }} must be prefixed to the src location
game_files:
    - { src: "app/descent2.ham", dest: "{{ base_dir }}/descent2.ham" }
    - { src: "app/descent2.hog", dest: "{{ base_dir }}/descent2.hog" }
    - { src: "app/descent2.s11", dest: "{{ base_dir }}/descent2.s11" }
    - { src: "app/descent2.s22", dest: "{{ base_dir }}/descent2.s22" }
    - { src: "app/alien1.pig", dest: "{{ base_dir }}/alien1.pig" }
    - { src: "app/alien2.pig", dest: "{{ base_dir }}/alien2.pig" }
    - { src: "app/fire.pig", dest: "{{ base_dir }}/fire.pig" }
    - { src: "app/groupa.pig", dest: "{{ base_dir }}/groupa.pig" }
    - { src: "app/ice.pig", dest: "{{ base_dir }}/ice.pig" }
    - { src: "app/water.pig", dest: "{{ base_dir }}/water.pig" }
    - { src: "app/intro-h.mvl", dest: "{{ base_dir }}/intro-h.mvl" }
    - { src: "app/other-h.mvl", dest: "{{ base_dir }}/other-h.mvl" }
    - { src: "app/robots-h.mvl", dest: "{{ base_dir }}/robots-h.mvl" }

# List of CD images that should be converted to OGG format
# format:
#   - { bin: "/relative/path/image.bin", cue: "/relative/path/image.cue", dest: "/full/path/dest" }
# bin and cue file locations are relative to tmp_dir.path
cd_images:
    - { bin: "app/descent_ii.gog", cue: "app/descent_ii.inst", dest: "{{ base_dir }}/music" }
