---
# X-COM Terror from the Deep role task
# This collection of tasks will install and configure X-COM
# Terror from the Deep to run with the open-source project
# OpenXcom

- name: Install OpenXcom
  ansible.builtin.import_role:
      name: openxcom

- name: Installing...
  ansible.builtin.include_role:
      name: install

