---
# INSTALL role main tasks.
#
# Description: Common set of tasks for all game installations supported by
#   Smoke.  The installation is broken down into 4 phases:
#


# Collect System information
#    This information is used to confirm the status of your system and the 
#    presence of the game files.  
- name: Collect System information
  block:
      # Check screen resolution to configure game to match your screen
      - name: Collect System Info
        ansible.builtin.include_tasks: collect_system_info.yml

      # Skip extracting if installer is not present on system
      - name: Perform stat on install file
        ansible.builtin.stat:
            path: "{{ installer.path }}"
        register: install_file

      # Skip extracting if game files are present on system
      - name: Perform stat on sanity file
        ansible.builtin.stat:
            path: "{{ sanity_file }}"
        register: is_game_installed

# Prerequisite system configurations needed to extract games
- name: Pre-Installation Requirements
  block:

      # Dependencies include programs needed by game
      - name: Install listed dependencies
        ansible.builtin.include_task: install_dependencies.yml
        when: dependencies is defined

      # Copying game files will fail if the directories do not exist
      - name: Create directory tree for game files
        ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
        loop: "{{ directories }}"
        loop_control:
            label: "{{ item }}"
        when: directories is defined

# Extract files from the installer into the appropriate location
- name: Extract game files from the installer
  block:

      - name: Create temporary working directory for installation files
        ansible.builtin.tempfile:
            state: directory
        register: tmp_dir

      - name: Extract MojoSetup files to temporary directory
        ansible.builtin.include_tasks: extract_mojo.yml
        when: installer.path is search(".sh")

      - name: Extract InnoSetup files to temporary directory
        ansible.builtin.include_tasks: extract_inno.yml
        when: installer.path is search(".exe")

      - name: Copy games files from the temporary directory
        ansible.builtin.include_tasks: copy_files.yml
        when: game_files is defined

      - name: Extract music tracks from cd image files
        ansible.builtin.include_tasks: rip_cd_tracks.yml
        loop: "{{ cd_images }}"
        loop_control:
            label: "{{ item.dest }}"
        when: cd_images is defined

  when:
      - not is_game_installed.stat.exists
      - install_file.stat.exists

  always:

      - name: Delete the temporary working directory
        ansible.builtin.file:
            path: "{{ tmp_dir.path }}"
            state: absent
        when: tmp_dir.path is defined

- name: Create the directories for Desktop Entries and Icons
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  loop:
      - "{{ app_dir }}"
      - "{{ icon_dir }}"

- name: Download missing desktop icons from smoke-repository
  ansible.builtin.get_url:
      url: "{{ icon_url }}/{{ item }}"
      dest: "{{ icon_dir }}/{{ item }}"
      force: no
  loop: "{{ icons }}"
  when: icons is defined
